# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Udit Gupta
tagline:          'Portfolio'
url:              https://sh0kunin.github.io/

author:
  name:           'Udit Gupta'
  github:         sh0kunin
  linkedin:       udit-gupta-598a093b
  facebook:       udit.gupta1
  instagram:      sh0kunin

paginate:         5

# Custom vars
version:          2.1.0

plugins: 
  - jekyll-paginate
  - jekyll-gist
  

